baseurl = "https://luneshao.github.io/"
# remember trailing / at end of baseurl
languageCode = "en-us"
title = "luneS's garden"
# Enable comments by entering your Disqus shortname
# disqusShortname = ""
# Enable Google Analytics by entering your tracking code
# googleAnalytics = ""
paginate = 15
theme = "hugo-lamp"
googleAnalytics = "UA-141781918-1"       # Google Analytics UA number

# [permalinks]
# 	post = "/:year/:month/:day/:slug"

# [params]
# 	name = "luneS"
# 	description = "卵はおいしいです"
# 	copyright = ""

# 	# Custom assets can be linked with their paths relative to static/
# 	custom_css = []
# 	custom_js  = []

# 	# Links to newer/older blog posts
# 	newer = "Newer"
# 	older = "Older"

# 	pageNotFoundTitle = "Page not found"
# 	pageNotFoundSubtitle = "The requested page was not <br> found on the server."

# [params.offcanvas]
# 	# Menu items
# 	title = "luneS"
# 	bio = "私は人間です"
# 	bio2 = "JiNan CN"
# 	subscribe = "Subscribe"
# 	followme = "Contact"

# 	# Enable Google search
# 	search_enabled = true
# 	search = "Search"

# 	[[params.offcanvas.socialnetworks]]
# 		name = "1561358258@qq.com"
# 		url = "mailto:1561358258@qq.com"
		
# [[menu.main]]
#   name = "Hugo"
#   weight = 1
#   identifier = "hugo"
#   url = "/hugo/"
[[menu.main]]
  name = "sina 微博"
  weight = 2
  identifier = "sina 微博"
  url = "https://www.weibo.com/u/3754246405"
# [[menu.main]]
#   name = "Tags"
#   weight = 3
#   identifier = "tags"
#   url = "/tags/"

[params]
  subtitle = "是一个人类。 :Q"
  author = "LuneShao"                     # Your name
  logo = "/img/photo.jpg"                  # Logo
  description = "卵はおいしいです"          # Meta description tag
  paginate = 10

  # SEO configs
  seotitle = "Lune's blogs luneshao lune"                  # Overwrite site title for SEO purpose
  googleSiteVerification = "Gu27F60AgLNf8h9KCAXsLXjKd7O-e1oZpSGeblt5w70"  # Google Webmaster
  msValidate = "bing_site_verification_code"                  # Bing Webmaster

	email = "1561358258@qq.com"
  github = "luneshao"
	twitter = "lune76308387"
	google = "LuneShao"
  disqusShortname = "luneshao"
  

  # Analytics settings
  # Baidu Analytics
# ba_track_id: 83e259f69b37d02a4633a2b7d960139c

  # Disqus settings（https://disqus.com/）
# disqus_username: qiubaiying